version: '3'
services:
    openeo-r-server:
        build:
            context: .
            dockerfile: DOCKERFILE
        image: openeo.gdalcubes:1.0.0
        container_name: openeo-r-server
        ports:
            - "8000:8000"
        volumes:
            - openeo-r-workspace:/var/openeo/workspace/
        restart: unless-stopped

volumes:
    openeo-r-workspace:
