FROM app3
MAINTAINER Rene Stalitza (r_stal01@uni-muenster.de)

RUN mkdir -p /opt/dockerfiles/ && mkdir -p /var/openeo/workspace/ && mkdir -p /var/openeo/workspace/data/ && mkdir -p /var/openeo/workspace/Demofiles/

COPY ./ /opt/dockerfiles/

COPY data/ /var/openeo/workspace/data

RUN Rscript -e "remotes::install_local('/opt/dockerfiles',dependencies=TRUE, force = TRUE)"

# cmd or entrypoint for startup
CMD ["R", "-q", "--no-save", "-f /opt/dockerfiles/Dockerfiles/start.R"]

EXPOSE 8000
